[firebase]
type = "service_account"
project_id = "questionpaper-c42fe"
private_key_id = "c2252026a47cb7a8b36381417f30a2befc663c26"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIn/O2O5OfiwRv
Lb9htEfn/TvjmJYEkrX7UaCfubmzzS7Bi1lFkoMweNzLmGLI0IZU491JRHp3Sv3H
sFNa8Imj+0JdWSyesB7K1uEaul683dBR9WvsglEXxxhhzCUPHYkt15eSlpFD+EdH
CAj/tuQ6VR7a0W2NzAnh5vikd1HE/jXVQR5nFx3dpgwxLvHttFfXrOxtnMcVh+Fb
RJkNEu44YnxUuNLu4UFnkbB+HZxG80yR8STvt0jd5wx8qimlWb1xUdNjXkO3bxcu
4y06Sjye3wKzMe4xbeuqtQ0I3RGxnIt5kMdJVIehPrOGsS1kwjXN14KpplMY8/3B
thAQV4CzAgMBAAECggEAH58CYSsjueZF5SYfP42UNc72lQlUP9VF5J45hGNYDyxc
XboScIJGtimel2Jl04P2YEPn+WfXK51Awawbfz5hW1y7WY44F6zntY3Hvhg43WjS
sFBP2d+yW16Qi72K68Z6fCS6aarcq4ti5KGyFWfksgL/kXqn200ZE6d9ciKyWyt0
NOtGj4fITI49H9qQ7d/WWiVXbqJhluIejzY6xKCc1pkkN3KtqdzsTJxwZXetd9ZZ
W4SbBecaIdclceuqpEdb3ehBp8URt0uMLz9hfcSvFbOc0luhJadq1AYH9FhNDZdg
3MMw+uZL9g50skc4wBCB0P9S2qIc5q+nPFO5RSXmYQKBgQD+IfXrtSRrFaovlRXv
ReW5jClBaxdpt3tuSOik5o5r+BlJ2NbHXeO4wz9Zf8RKQ/t5pZc+gs4oShv2xrAn
W5wmxuSsoz2T4r8RCFD0U3wxJr/daMOHK3qVxszDF0M//ZqgTxx/59XXRVR6RXV/
ZJzx8eRF7uUSlNpde/3N3ScjIQKBgQDKGVb7p/B/MtYjEQ7kSPEsVDiMMTrZES2D
D6m8o6O2QPr5GIQ/65V6B/6YuK5UN4nEucTp63BrPRtDrrABEzRorG5HB7vUyUSw
C73VygO93OX+nfPWCI0avwVSuFt3eDHJ894StsFY5vB80ifwY18y/nUhca6Qgmat
9zT9sIB9UwKBgQDSqeZJIVzyJABy9zw6oA+h801TvGmpKf942Zl48OKJIB4eeFD6
7ZrTU48VKvPVuGsjWSB6IkaxYVWzCNuHlMpp3qA7eAqYp/NJNEKfdwFRYVTVPn4v
c9xngmfFJWiLCDiAwXPXl6BNllxEC4YuN4Jeke1wB2v/LkOiESHA4J4L4QKBgCaz
b4rFgDJ7g7I3ZAinRzfb8PA3xTMoLPT6HOD43TLbgrQM09aBwKAbw89vHkMWV5WK
lYDOCzsd+oidfSrXiKO60WtcucVnvXWQ6gt0of7LvGdjy/viq1LB3b0XfLyGEdLA
lngy8xeZMdhVTjykauiS/c8nu+wEbLFHs6gZEqHtAoGBAIgyF4HGc5kfcIqpyODU
7QIWRUe8OhvGwNZwURZo64p8o2Nms/4drH1l32tZYdqKejAWmVVdcoYhptKr+n+/
BisSw4c/dlrXuJLh/CQq/j+fgAaHYjV+Y9UTD1A/yUj7DXw6TAJfVdMrAhtvPS9D
2zDoKMyjmQeCfkYv77AyiheW
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@questionpaper-c42fe.iam.gserviceaccount.com"
client_id = "104952973111612864965"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40questionpaper-c42fe.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
